# Generated by Django 2.0.1 on 2018-01-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0002_auto_20180130_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('rev_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Item', verbose_name='해당 제품')),
            ],
        ),
    ]
