# Generated by Django 2.0.1 on 2018-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180203_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='profile/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
