# Generated by Django 2.0.1 on 2018-02-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180203_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
