# Generated by Django 2.0.1 on 2018-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_creator_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creator_header_img',
            field=models.ImageField(blank=True, null=True, upload_to='creator/%Y/%m/%d/'),
        ),
    ]
