# Generated by Django 2.0.1 on 2018-02-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0004_auto_20180203_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='wiki')),
                ('item', models.ManyToManyField(blank=True, null=True, to='creator.Item')),
            ],
        ),
    ]
