# Generated by Django 2.0.1 on 2018-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='행사 이름')),
                ('place', models.CharField(max_length=30, verbose_name='행사 장소')),
                ('date', models.DateField(verbose_name='행사 날짜')),
                ('time', models.TimeField(verbose_name='행사 시간')),
                ('content', models.TextField(verbose_name='행사 설명')),
                ('tag2', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='행사 성격 태그')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='event.Tag', verbose_name='태그'),
        ),
    ]
