# Generated by Django 2.0.1 on 2018-01-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='상품 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('youtube_url', models.URLField(verbose_name='링크')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('item', models.ManyToManyField(blank=True, null=True, to='creator.Item', verbose_name='제품')),
            ],
        ),
    ]
