# Generated by Django 2.0.1 on 2018-02-03 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_youtube_content_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Youtube_Content', to=settings.AUTH_USER_MODEL),
        ),
    ]
