# Generated by Django 2.0.1 on 2018-02-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_auto_20180220_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_item', to='creator.Brand', verbose_name='브랜드명'),
        ),
    ]
