# Generated by Django 2.0.1 on 2018-02-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180220_1438'),
        ('creator', '0009_auto_20180220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='skin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.SkinType', verbose_name='skin_type_item'),
        ),
    ]
