# Generated by Django 2.0.1 on 2018-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180124_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hastag',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
